### ISSUE TITLE
[Doc]: Fix issue #972: Add Readme.md to packages/rrewb 

### ISSUE THREAD

**Issue by HurricaHjz** [HurricaHjz/rrweb_2120_ga_3#1]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/rrweb-io/rrweb/issues) for a feature request that matches the one I want to file, without success.

### What package is this feature request for?

rrweb

### Problem Description

If you head to https://www.npmjs.com/package/rrweb there is no description of the project because /packages/rrweb doesn't have a README.md

### Proposed Solution

Add READNE.md

### Alternatives Considered

No alternative

### Additional Information

No response

**Comment by fengyun5264** [comment]
This issue has been resolved through the pull request https://github.com/rrweb-io/rrweb/pull/1025 in the original repo
