### ISSUE TITLE
[Bug]: Show controls in fullscreen mode for rrweb-player

### ISSUE THREAD

**Issue by MengZihan712** [HurricaHjz/rrweb_2120_ga_3#2]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/rrweb-io/rrweb/issues) for a bug report that matches the one I want to file, without success.

### What package is this bug report for?

rrweb

### Version

v1.0.0

### Expected Behavior

Show controls and progress bar in fullscreen mode for rrweb-player

### Actual Behavior

No progress bar in fullscreen mode for rrweb-player.

### Steps to Reproduce

Check and modify the component code.

**Comment by fengyun5264** [comment]
This issue has been resolved through the pull request https://github.com/rrweb-io/rrweb/pull/1028
